### ISSUE TITLE
Container crashes

### ISSUE THREAD

**Issue by ValdasK** [NebulousLabs/docker-sia#28]
Been running for a week or so just fine, and now I get the following when trying to start:

```
Sia Daemon v1.4.11
Git Revision 026f95f65
Loading...
(1/6) Loading siad...
(2/6) Loading gateway...
(3/6) Loading consensus...
(4/6) Loading transaction pool...
(5/6) Loading wallet...
(6/6) Loading host...
API is now available, synchronous startup completed in 5.633 seconds
Finished full setup in 23.168 seconds
panic: runtime error: index out of range [2] with length 2

goroutine 1028 [running]:
gitlab.com/NebulousLabs/Sia/modules/host.revisionFromRequest(0x70c196fab90ffa5a, 0xa91b4eb77e886c89, 0xbd1f5af35971db60, 0xd02d491b8bd04269, 0x0, 0xc0001643c0, 0x2, 0x4, 0x2, 0xffffffffffffffff, ...)
	gitlab.com/NebulousLabs/Sia@/modules/host/payment.go:252 +0x432
gitlab.com/NebulousLabs/Sia/modules/host.(*Host).managedPayByContract(0xc000096700, 0x103c1c0, 0xc00236a000, 0x0, 0x0, 0x0, 0x0)
	gitlab.com/NebulousLabs/Sia@/modules/host/payment.go:92 +0x461
gitlab.com/NebulousLabs/Sia/modules/host.(*Host).ProcessPayment(0xc000096700, 0x103c1c0, 0xc00236a000, 0xc00025a300, 0x0, 0x0, 0x0)
	gitlab.com/NebulousLabs/Sia@/modules/host/payment.go:31 +0x20f
gitlab.com/NebulousLabs/Sia/modules/host.(*Host).managedRPCUpdatePriceTable(0xc000096700, 0x103c1c0, 0xc00236a000, 0xc000344f90, 0x0)
	gitlab.com/NebulousLabs/Sia@/modules/host/rpcupdatepricetable.go:126 +0x27b
gitlab.com/NebulousLabs/Sia/modules/host.(*Host).threadedHandleStream(0xc000096700, 0x103c1c0, 0xc00236a000)
	gitlab.com/NebulousLabs/Sia@/modules/host/network.go:389 +0x6a3
gitlab.com/NebulousLabs/siamux.(*SiaMux).threadedAccept.func2(0xc0000534c0, 0xc00236a000, 0xc00000c780)
	gitlab.com/NebulousLabs/siamux@v0.0.0-20200529161118-72d7f2cfd76d/listener.go:186 +0x3c
created by gitlab.com/NebulousLabs/siamux.(*SiaMux).threadedAccept
	gitlab.com/NebulousLabs/siamux@v0.0.0-20200529161118-72d7f2cfd76d/listener.go:185 +0x450
```

**Comment by jkawamoto** [comment]
Hopefully, this will be fixed in the next release: https://gitlab.com/NebulousLabs/Sia/-/issues/4215.

**Comment by ro-tex** [comment]
This should be fixed by the mentioned Sia issue.
